export const WATCH_CHATS_INCOMING_TYPE = 'WATCH_CHATS' as const;
export const SUBSCRIBED_CHAT_INCOMING_TYPE = 'SUBSCRIBED_CHAT' as const;

export const PUBLISH_MESSAGE_OUTGOING_TYPE = 'PUBLISH_MESSAGE' as const;
export const SUBSCRIBE_CHAT_OUTGOING_TYPE = 'SUBSCRIBE_CHAT' as const;
